version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: development
  assignees:
  - lukeshiner
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: requests-mock
    versions:
    - 1.9.0
  - dependency-name: tox
    versions:
    - 3.21.4
    - 3.22.0
