language: python
python:
  - "3.6"
  - "3.7"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - make init
# command to run tests
script:
  - make test
