version: 1

update_configs:
  - package_manager: "python"
    directory: ""
    update_schedule: "live"
    default_assignees:
      - "lukeshiner"
    version_requirement_updates: "off"
    target_branch: "development"
